version: 2
updates:
- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: weekly
    time: "09:00"
    timezone: "America/Los_Angeles"
  open-pull-requests-limit: 10
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: weekly
    time: "09:00"
    timezone: "America/Los_Angeles"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
    time: "09:00"
    timezone: "America/Los_Angeles"
  open-pull-requests-limit: 10
