[env]
CARGO_MAKE_RELEASE_FLOW_TARGET = "${{ matrix.binary_target }}"
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
CARGO_MAKE_RUN_CLIPPY = true
CARGO_MAKE_CLIPPY_ARGS = "--all-features -- -D warnings"
CARGO_MAKE_RUN_CHECK_FORMAT = true
RUSTFLAGS="-D warnings"

[tasks.check-format-ci-flow]
condition = { env_set = [
	"CARGO_MAKE_RUN_CHECK_FORMAT",
], channels = [
	"stable",
], platforms = [
	"linux",
] }

[tasks.clippy-ci-flow]
condition = { env_set = [
	"CARGO_MAKE_RUN_CLIPPY",
], channels = [
	"stable",
], platforms = [
	"linux",
] }
