[package]
name = "swiftnav"
version = "0.8.3"
authors = ["Swift Navigation <dev@swiftnav.com>"]
edition = "2018"
description = "GNSS positioning and related utilities"
readme = "README.md"
repository = "https://github.com/swift-nav/swiftnav-rs"
license = "LGPL-3.0"
rust-version = "1.62.1"

[dependencies]
rustversion = "1.0"
chrono = { version = "0.4", optional = true }
swiftnav-sys = { version = "^0.8.1", path = "../swiftnav-sys/" }

[dev-dependencies]
float_eq = "1.0.1"
